config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}
  resources :testsessions, only: :create
  resources :users, :only => [:index, :show]

   devise_scope :user do
     root :to => "devise/sessions#new"
     get 'login', to: 'devise/sessions#new'
     delete 'logout', to: 'devise/sessions#destroy'
     get '/index', to: 'pages#index'
   end
    root 'pages#index'
    get '/index', to: 'pages#index'
    get 'pages/show',to: 'pages#show', as: 'profile'
    get '/search', to: 'pages#search'
    get '/about', to:'pages#about'

    put 'users/follow/:user_id' => 'users#follow'
    put 'users/unfollow/:user_id' => 'users#unfollow'

    get 'users/follow_list/:user_id' => 'users#follow_list'
    get 'users/follower_list/:user_id' => 'users#follower_list'
   resources :microposts,          only: [:create, :destroy, :show]

   get '/search', to:"itunessearch#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  #validates :content, presence: true
  #validates :artistname, presence: true
  #validates :albumtitle, presence:true
  validate :add_error_sample

  def add_error_sample
    # nameが空のときにエラーメッセージを追加する
    if albumtitle.blank?
      errors[:base] << "・アルバムタイトルが空欄です"
    end

    # 価格が空のときにエラーメッセージを追加する
    if content.blank?
      errors[:base] << "・投稿文が空欄です"
    end
  end
end

app/controllers/microposts_controller.rb
require 'net/https'
require 'uri'
require 'json'
class MicropostsController < ApplicationController
  before_action :authenticate_user!, only:[:create, :destroy]
  before_action :correct_user, only: :destroy
  def create
      # hash形式でパラメタ文字列を指定し、URL形式にエンコード
      artistterm = params[:artistname]
      albumterm = params[:albumtitle]
      params = URI.encode_www_form({ term: "#{artistterm} #{albumterm}" ,country: 'jp' ,
            media: 'music' , entity: 'album' ,lang: 'ja_jp', limit: '10'})
      # URIを解析し、hostやportをバラバラに取得できるようにする
      uri = URI.parse("https://itunes.apple.com/search?#{params}")
      # リクエストパラメタを、インスタンス変数に格納
      @query = uri.query

      # 新しくHTTPセッションを開始し、結果をresponseへ格納
        https = Net::HTTP.new(uri.host, uri.port)
        https.use_ssl = true
        https.verify_mode = OpenSSL::SSL::VERIFY_NONE
        response = https.start do |http|
          # 接続時に待つ最大秒数を設定
          http.open_timeout = 5
          # 読み込み一回でブロックして良い最大秒数を設定
          http.read_timeout = 10
          # ここでWebAPIを叩いている
          # Net::HTTPResponseのインスタンスが返ってくる
          http.get(uri.request_uri)
        end

      # 例外処理の開始
      begin
        # responseの値に応じて処理を分ける
        case response
        # 成功した場合
        when Net::HTTPSuccess
          # responseのbody要素をJSON形式で解釈し、hashに変換
          @result = JSON.parse(response.body)
          # 表示用の変数に結果を格納
          @artistname = @result["results"][0]["artistName"]
          @trackname = @result["results"][0]["collectionName"]
          @artworkUrl100 = @result["results"][0]["artworkUrl100"]
          #画像のリサイズ
          @resizeimg = @artworkUrl100.gsub(/100x100/, '200x200')
        # 別のURLに飛ばされた場合
        when Net::HTTPRedirection
          @message = "Redirection: code=#{response.code} message=#{response.message}"
        # その他エラー
        else
          @message = "HTTP ERROR: code=#{response.code} message=#{response.message}"
        end
      # エラー時処理
      rescue IOError => e
        @message = "e.message"
      rescue TimeoutError => e
        @message = "e.message"
      rescue JSON::ParserError => e
        @message = "e.message"
      rescue => e
        @message = "e.message"
      end
      #投稿データの保存
    @micropost = current_user.microposts.build(artistname: @artistname, albumtitle: @trackname,
                artworkimg: @resizeimg,content: micropost_params[:content])
    if @micropost.save
      redirect_to index_path, notice: "投稿しました"
    else
      flash.now[:alert] = "投稿できませんでした"
      @user = current_user
      @feed_items = current_user.feed.paginate(page: 1)
      render 'pages/index'
    end
  end

  def destroy
    @micropost.destroy
    flash[:notice] = "削除しました"
    redirect_to request.referrer || root_url
  end

  def show
    @micropost = Micropost.find(params[:id])
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content,:artistname,:albumtitle)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li class="list-inline-item micropost" id = "micropost-<%= micropost.id %>">
    <!--<span class="icon">
    <%# unless @user.image.nil? %>
    <img src= <%#= @user.image %>>
    <%#else%>
    <%#= image_tag('/assets/nonicon.png') %>
    <%# end %>
    </span>-->
    <ul class="list-inline">
    <li class="list-inline-item">
    <%= link_to micropost_path(micropost.id), remote: true, class: "modal-open" do%>
      <img src=<%= micropost.artworkimg %> class="artwork">
    <% end %>
    <div id="micropost-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
    </li>
    <li class="list-inline-item">
    <div class="row">
    <p class="content"><%= micropost.content %></p>
    <div class="micropost-delete">
    <% if current_user == micropost.user %>
      <%= link_to micropost, method: :delete,
                                 data: { confirm: "削除しますか？" }, class: "micropost-delete" do%>
        <%= image_tag('trash.png') %>
      <% end %>
    <% end %>
    </div>
    </div>
    </li>
    </ul>
</li>

app/views/microposts/_micropost_error_messages.html.erb
<% if @micropost.errors.any? %>
    <% @micropost.errors.full_messages.each do |message| %>
      <li id="micropost-error"><%= message %></li>
    <% end %>
<% else %>
  <div class="mt-5"></div>
<% end %>

app/views/microposts/_searchbutton.html.erb
<input type="button" id="search_button" value="Search" class="btn btn-info btn-sm pull-left">

app/views/microposts/_searchresult.html.erb
    <div class="col-md-3 search">
    <div class="row">
    <div id="image-box"><img /></div><p id="searchresult"></p></div>
    <p class="searchresult"><span id="artistname"></span></p>
        <p class="searchresult"><span id="albumtitle"></span></p>
        </div>

app/views/microposts/_show.html.erb
<div class="modal-dialog modal-dialog-centered ">
  <div class="modal-content">
   <div class="row modal_micropost_content">
    <div class="col-md-6">
    <img src=<%= @micropost.artworkimg %> class="artwork">
    </div>
    <div class="col-md-6">
    <h2><%= @micropost.artistname %></h2>
    <h3><%= @micropost.albumtitle %></h3>
    <h2><%= @micropost.content %></h2>
    <p>Posted by <%= @micropost.user.username %></p>
    </div>
    </div>
  </div>
</div>

app/views/microposts/show.js.erb
$("#micropost-modal").html("<%= escape_javascript(render 'microposts/show') %>");
$("#micropost-modal").modal("show");