config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks"}
  resources :testsessions, only: :create
  resources :users, :only => [:index, :show]

   devise_scope :user do
     root :to => "devise/sessions#new"
     get 'login', to: 'devise/sessions#new'
     delete 'logout', to: 'devise/sessions#destroy'
     get '/index', to: 'pages#index'
   end
    root 'pages#index'
    get '/index', to: 'pages#index'
    get 'pages/show',to: 'pages#show', as: 'profile'
    get '/search', to: 'pages#search'
    get '/about', to:'pages#about'

    put 'users/follow/:user_id' => 'users#follow'
    put 'users/unfollow/:user_id' => 'users#unfollow'

    get 'users/follow_list/:user_id' => 'users#follow_list'
    get 'users/follower_list/:user_id' => 'users#follower_list'
   resources :microposts,          only: [:create, :destroy, :show]

   get '/search', to:"itunessearch#search"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse　navbar-expand-sm">
  <div class="container">
    <% if user_signed_in? %>
    <%= link_to "EmojiRecords", index_path, id:"logo" %>
    <% else %>
    <%= link_to "EmojiRecords", root_path, id:"logo" %>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
                 <li><%= link_to "Home", index_path %></li>
                 <li><%= link_to "Users", users_path %></li>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                     Account <b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                     <li><%= link_to "Profile", current_user %></li>
                     <% if current_user != User.find_by(email:"test@test.com") %>
                     <li><%= link_to "Settings", edit_user_registration_path %></li>
                     <% end %>
                     <li class="divider"></li>
                     <li>
                       <%= link_to "Log out", logout_path, method: :delete %>
                     </li>
                   </ul>
                 </li>
               <% else %>
                 <li><%= link_to "Home", root_path %></li>
                 <li><%= link_to "About", about_path %></li>
                 <li><%= link_to "Log in", login_path %></li>
               <% end %>
        </ul>
      </nav>
    </div>
  </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application'%>
<%= render 'layouts/shim' %>
  </head>
  <body>
<%= render 'layouts/header' %>
      <%= render 'shared/flash' %>
            <%= yield %>
<%# <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>